name: Sync
#https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github
#https://dev.to/n3wt0n/3-ways-to-sync-a-forked-repository-on-github-automatically-cfd
#https://github.com/nektos/act
# Once a week on Friday
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 5'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps: 
      - name: Sync and merge with upstream
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: "https://github.com/pterodactyl/panel.git"
          upstream_branch: "develop"
          downstream_branch: "develop"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Pterodactyl Release
        uses: rez0n/actions-github-release@v1.8
        id: pt_r
        env: 
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "pterodactyl/panel"
          type: "stable"
      - name: Fetch Titanhosting Release
        uses: rez0n/actions-github-release@v1.8
        id: th_r
        env: 
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "VisualSource/pterodactyl-panel"
          type: "stable"
      - name: Test Versions
        uses: madhead/semver-utils@1.0.0
        id: version
        with:
          version: ${{steps.pt_r.outputs.release }}
          compare-to: ${{ steps.th_r.outputs.release}}  
      - name: Check Out
        if: ${{ '>' == steps.version.outputs.comparison-result }}
        uses: actions/checkout@v3  
      - name: Create Tag
        if: ${{ '>' == steps.version.outputs.comparison-result }}
        uses: rickstaa/action-create-tag@v1.3.7
        with:
          tag: ${{format('{0}-a', steps.pt_r.outputs.release)}}